### ISSUE TITLE
compiling in opensuse

### ISSUE THREAD

**Issue by sboschi** [jasonmc/forked-daapd#2]
Hi,
I am trying to compile in opensuse.
I have found all needed libraries (some issues with antlr3 that I managed to solve taking the package from the opensuse factory) but now I am stuck with libavl. There is no rpm for this package and so I thought I need to compile it. It is not clear which is the source code I need to compile. I thought could be this http://libavl.sourcearchive.com/downloads/0.3.5/ or version 0.4 found somewhere else (cannot find it anymore where :-) )

stefano@desktop:~/src/avl-0.4> sudo make install  
root's password:  
install -m 644 libavl.so /usr/local/lib/libavl.so.0.4  
install -m 644 libavl.a /usr/local/lib/libavl.a.0.4  
install -m 644 avl.h /usr/local/include/avl.h  
ln -sf libavl.so.0.4 /usr/local/lib/libavl.so.  
ln -sf libavl.so. /usr/local/lib/libavl.so  
ln -sf libavl.a.0.4 /usr/local/lib/libavl.a.  
ln -sf libavl.a. /usr/local/lib/libavl.a  
stefano@desktop:~/src/avl-0.4> ls  
AUTHORS  avl.c  avl.h  avl_test.c  avl_test.cpp  CHANGES  COPYING  debian  INSTALL  libavl.a  libavl.so  Makefile  Makefile.cygwin  README  TODO  
stefano@desktop:~/src/avl-0.4> sudo cp *.h /usr/include/

All seems ok, so I moved back to configure:

stefano@desktop:~/src/forked-daapd> ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-flac --enable-musepack
[...]
checking avl.h usability... yes
checking avl.h presence... yes
checking for avl.h... yes
checking for avl_alloc_tree in -lavl... no
configure: error: libavl not found

**Comment by sboschi** [comment]
libavl 0.4 source was found here http://home.fazekas.hu/~nagydani/avl/
trying to install 0.3.5 gives an error

stefano@desktop:~/src/avl-0.3.5> sudo make install
root's password:
/usr/bin/install -d /usr/local/lib
/usr/bin/install avl.h /usr/local/include
/usr/bin/install  /usr/local/lib
/usr/bin/install: missing destination file operand after `/usr/local/lib'
Try`/usr/bin/install --help' for more information.

**Comment by sboschi** [comment]
Me again, I have compiled libavl 0.3.5 and made a manual install

stefano@desktop:/usr/local/lib> ls -als
total 1072
  4 drwxr-xr-x  4 root root   4096 2010-03-27 14:14 .
  4 drwxr-xr-x 10 root root   4096 2009-11-03 00:43 ..
120 -rw-r--r--  1 root root 121962 2010-03-26 23:17 libantlr3c.a
  4 -rwxr-xr-x  1 root root    803 2010-03-26 22:42 libantlr3c.la
100 -rwxr-xr-x  1 root root 100323 2010-03-26 22:42 libantlr3c.so
  0 lrwxrwxrwx  1 root root     10 2010-03-27 14:05 libavl.so -> libavl.so.
  0 lrwxrwxrwx  1 root root     13 2010-03-27 14:04 libavl.so. -> libavl.so.1.5
  0 lrwxrwxrwx  1 root root     13 2010-03-27 14:09 libavl.so.1 -> libavl.so.1.5
 12 -rwxr-xr-x  1 root root  10221 2010-03-27 14:02 libavl.so.1.5

configure is now happy and after having installed flac-devel package I coud run 'make'.
Now the problems seems to be antlr3 / java

antlr3  RSP.g
Exception in thread "main" java.lang.NoClassDefFoundError: antlr/Tool
Caused by: java.lang.ClassNotFoundException: antlr.Tool
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: antlr.Tool.  Program will exit.

**Comment by sboschi** [comment]
closing this thread ...
